server:
  dev:
    enabled: true
  standalone:
    enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    enabled: true
    type: ClusterIP

injector:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

ui:
  enabled: true
  serviceType: ClusterIP
  serviceNodePort: null
  externalPort: 8200
