jenkins:
  systemMessage: "Jenkins configured automatically by Terraform"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin" # In production, use a secure password
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "devops-tools"
        jenkinsUrl: "http://jenkins:8080"
        jenkinsTunnel: "jenkins-agent:50000"
        containerCapStr: "10"
        maxRequestsPerHostStr: "32"
        retentionTimeout: 5
        connectTimeout: 5
        readTimeout: 15
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                scope: GLOBAL
                id: "vault-token"
                secret: "${vault_token.jenkins.client_token}"
                description: "Vault token for Jenkins"
